Repository SourcePointUSA/android-cmp-app, pull requests merged in 2023-09, with the labels that each got.

#685 [DIA-2542] Local data versioning
  cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/data/local/DataStorageImplTest.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/campaign/CampaignManager.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorage.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageGdpr.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModel.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModelExt.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManager.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/ServiceImplTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModelTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManagerTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/util/SpUtilsTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/web/WebConsentTransferTestActivityTest.kt
Labels: ✔️ ready for release

#688 [DIA-2628] Needs to handle no-internet better
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/core/web/ConsentWebView.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Builder.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/CreationalUtility.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Factory.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/NetworkClientImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/connection/ConnectionManager.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/connection/ConnectionManagerImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/util/ConnectionExt.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/exception/ExceptionDescriptions.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/exception/Exceptions.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/ViewsManager.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/SpConsentLibImplTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/NetworkClientImplTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/util/ViewsManagerImplTest.kt
  samples/app/src/main/AndroidManifest.xml
  samples/metaapp/src/main/AndroidManifest.xml
  samples/native-message-demo/src/main/AndroidManifest.xml
  samples/ott-message-demo/src/main/AndroidManifest.xml
  samples/web-message-demo/src/main/AndroidManifest.xml
Labels: 🔎 review required

#695 [DIA-2762] UI tests fix
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinNativeMessage.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinNativeOttTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinOldConsentTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinOttTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/SpClientMock.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestData.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/web/WebConsentTransferTestActivityTest.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/NativeMessageActivity.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/di/AppModule.kt
  samples/metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/MainActivityTest.kt
  ui-test-util/src/main/java/com/example/uitestutil/EspressoUtils.kt
  ui-test-util/src/main/java/com/example/uitestutil/TestUtils.kt
Labels: 🛠️ work in progress
