Repository SourcePointUSA/android-cmp-app, pull requests merged in 2023-07, with the labels that each got.

#658 [DIA-2198] Manipulate CCPA consent string based on applies
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/campaign/CampaignManager.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorage.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageCcpa.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModel.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModelExt.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/SpUtils.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/campaign/CampaignManagerTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/converter/JsonConverterImplTest.kt
Labels: ✔️ ready for release

#659 [DIA-2360] Fix message showing multiple times on reconsent flow
  cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/SpUtilsTest.kt
  cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/data/local/DataStorageCcpaImplTest.kt
  cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/data/local/DataStorageGdprImplTest.kt
  cmplibrary/src/androidTest/java/com/sourcepoint/cmplibrary/data/local/DataStorageImplTest.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/campaign/CampaignManager.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorage.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageCcpa.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageGdpr.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/local/DataStorageImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/NetworkClient.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/NetworkClientImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/ConsentStatusApiModel.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/MessagesApiModelExt.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/PvDataApiModel.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/model/optimized/PvDataApiModelExt.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/network/util/HttpUrlManager.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/campaign/CampaignManagerTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/ServiceImplTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/NetworkClientImplTest.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/network/TestUtilGson.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinNativeMessage.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinOttTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinTest.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/SpClientMock.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestData.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/TestUseCase.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/web/WebConsentTransferTestActivityTest.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/di/AppModule.kt
  samples/metaapp/src/androidTest/java/com/sourcepointmeta/metaapp/MainActivityTest.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/util/DefaultProperties.kt
  ui-test-util/jsonFiles/v6_stored_consent/stored_consent_ccpa.json
  ui-test-util/jsonFiles/v6_stored_consent/stored_consent_gdpr.json
  ui-test-util/jsonFiles/v6_stored_consent/stored_consent_gdpr_ccpa.json
  ui-test-util/jsonFiles/v7/message_body_cs.json
  ui-test-util/src/main/java/com/example/uitestutil/TestUtils.kt
Labels: 🔎 review required

#663 [DIA-2263] Create confluence page for the SDK release process
  README.md
Labels: 🔧 small changes

#667 [DIA-2449] Not call onError if pv-data fails
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/Service.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/data/ServiceImpl.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/data/ServiceImplTest.kt
Labels: ✔️ ready for release

#668 [DIA-2447] Update project dependencies
  cmplibrary/build.gradle.kts
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/AuthIdUtils.kt
  samples/app/build.gradle
  samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/NativeMessageActivity.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/tv/detail/DetailPropertyFragment.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/tv/properties/PropertyListFragmentTv.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/tv/viewer/JsonViewerActivityTv.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/demo/DemoActivity.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/ui/propertylist/PropertyListFragment.kt
  samples/native-message-demo/src/main/java/com/sourcepoint/app/v6/NativeMessageActivity.kt
Labels: 🛠️ work in progress
