Repository SourcePointUSA/android-cmp-app, pull requests merged in 2024-04, with the labels that each got.

#796 [DIA-3574] Update SDK dependencies V1
  .github/workflows/feature-tests.yml
  .github/workflows/instrumentation_tests.yml
  .github/workflows/metaap_instrumentation_tests.yml
  .github/workflows/release-testing.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  build.gradle
  cmplibrary/build.gradle.kts
  cmplibrary/src/androidTest/AndroidManifest.xml
  cmplibrary/src/main/AndroidManifest.xml
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  samples/app/build.gradle
  samples/metaapp/build.gradle.kts
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/App.kt
  samples/native-message-demo/build.gradle
  samples/ott-message-demo/build.gradle
  samples/web-message-demo/build.gradle
  ui-test-util/build.gradle
Labels: 🛠️ work in progress

#715 [DIA-2066] Back button MetaApp AndroidTv
  README.md
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLib.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/SpConsentLibImpl.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/core/web/ConsentWebView.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/core/web/IConsentWebView.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/SpBackPressOttDelegate.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/util/ViewsManager.kt
  samples/app/src/androidTest/java/com/sourcepoint/app/v6/MainActivityKotlinOttTest.kt
  samples/app/src/main/java/com/sourcepoint/app/v6/MainActivityKotlin.kt
  samples/metaapp/src/main/java/com/sourcepointmeta/metaapp/tv/demo/DemoActivityTv.kt
Labels: ✔️ ready for release

#803 remove unused code from ConsentManagerUtils
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/consent/ConsentManagerUtils.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Builder.kt
  cmplibrary/src/main/java/com/sourcepoint/cmplibrary/creation/Factory.kt
  cmplibrary/src/test/java/com/sourcepoint/cmplibrary/consent/ConsentManagerUtilsImplTest.kt
Labels: 🔧 refactoring
